# Generated by Django 6.0.4 on 2026-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('role', models.SmallIntegerField(choices=[(1, '辅导员'), (2, '批改员'), (3, '超级管理员')], default=1, verbose_name='角色')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
