# Generated by Django 6.0.4 on 2026-05-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0004_add_ai_grade_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, default='', max_length=50, verbose_name='供应商名称')),
                ('api_url', models.CharField(blank=True, default='', max_length=500, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API 密钥')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.1, verbose_name='温度参数')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大输出 Token')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='系统提示词')),
                ('is_active', models.BooleanField(default=False, verbose_name='全局启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 批改配置',
                'verbose_name_plural': 'AI 批改配置',
                'db_table': 'ai_grade_config',
            },
        ),
        migrations.CreateModel(
            name='AIGradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('prompt_sent', models.TextField(verbose_name='发送的 Prompt')),
                ('response_raw', models.TextField(blank=True, default='', verbose_name='原始返回')),
                ('score_returned', models.IntegerField(blank=True, null=True, verbose_name='AI 返回分数')),
                ('remark_returned', models.CharField(blank=True, default='', max_length=500, verbose_name='AI 返回评语')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examanswer', verbose_name='答案')),
            ],
            options={
                'verbose_name': 'AI 批改日志',
                'verbose_name_plural': 'AI 批改日志',
                'db_table': 'ai_grade_log',
            },
        ),
    ]
