# Generated by Django 6.0.4 on 2026-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0001_add_ai_grade_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigradelog',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='状态'),
        ),
    ]
