# Generated by Django 6.0.4 on 2026-05-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='导入文件名')),
                ('import_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='导入类型')),
                ('total_rows', models.IntegerField(blank=True, null=True, verbose_name='总行数')),
                ('success_rows', models.IntegerField(blank=True, null=True, verbose_name='成功数')),
                ('fail_rows', models.IntegerField(blank=True, null=True, verbose_name='失败数')),
                ('error_detail', models.TextField(blank=True, null=True, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '导入记录',
                'verbose_name_plural': '导入记录',
                'db_table': 'import_records',
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='模板ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multi', '多选题'), ('judge', '判断题'), ('essay', '简答题')], max_length=20, verbose_name='题型')),
                ('stem', models.CharField(max_length=500, verbose_name='题干模板')),
                ('param_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='参数字段')),
                ('explanation', models.CharField(blank=True, max_length=500, null=True, verbose_name='题目解析')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '题目模板',
                'verbose_name_plural': '题目模板',
                'db_table': 'question_templates',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('module', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作模块')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='动作')),
                ('target', models.CharField(blank=True, max_length=200, null=True, verbose_name='操作对象')),
                ('content', models.TextField(blank=True, null=True, verbose_name='日志详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_logs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别')),
                ('college', models.CharField(blank=True, max_length=100, null=True, verbose_name='学院')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='年级')),
                ('class_name', models.CharField(blank=True, db_column='class', max_length=50, null=True, verbose_name='班级')),
                ('advisor_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='辅导员姓名')),
                ('advisor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='辅导员电话')),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True, verbose_name='民族')),
                ('native_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='籍贯')),
                ('origin_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='生源地')),
                ('family_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭所在地')),
                ('household_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='户籍所在地')),
                ('is_academic_difficulty', models.BooleanField(default=False, verbose_name='是否学业困难')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='宗教信仰')),
                ('dorm_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='住宿地址')),
                ('off_campus_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='校外住宿地址')),
                ('is_financial_difficulty', models.BooleanField(default=False, verbose_name='是否经济困难')),
                ('enrollment_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='学籍状态')),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='照片地址')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='辅导员')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'students',
                'indexes': [models.Index(fields=['advisor_name'], name='students_advisor_c6416a_idx'), models.Index(fields=['class_name'], name='students_class_50de96_idx'), models.Index(fields=['college'], name='students_college_aeac2a_idx')],
            },
        ),
    ]
