# Generated by Django 6.0.4 on 2026-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业'),
        ),
    ]
