# Generated by Django 6.0.4 on 2026-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='辅导员工号'),
        ),
    ]
