# Generated by Django 6.0.4 on 2026-05-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='考试ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('start_time', models.DateTimeField(verbose_name='考试开始时间')),
                ('duration_minutes', models.IntegerField(verbose_name='考试时长（分钟）')),
                ('status', models.SmallIntegerField(choices=[(0, '未发布'), (1, '进行中'), (2, '已结束'), (3, '已关闭')], default=0, verbose_name='考试状态')),
                ('question_config', models.JSONField(blank=True, null=True, verbose_name='考试题型配置快照')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='CheatLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='异常类型')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='补充说明')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '防作弊日志',
                'verbose_name_plural': '防作弊日志',
                'db_table': 'cheat_logs',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='题目ID')),
                ('question_text', models.CharField(max_length=2000, verbose_name='题干')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multi', '多选题'), ('judge', '判断题'), ('essay', '简答题')], max_length=20, verbose_name='题型')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='选项内容')),
                ('correct_answer', models.CharField(blank=True, max_length=500, null=True, verbose_name='标准答案')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='题号顺序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='考试')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.student', verbose_name='学生')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.questiontemplate', verbose_name='题目模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考试题目',
                'verbose_name_plural': '考试题目',
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='答案ID')),
                ('content', models.CharField(blank=True, max_length=2000, null=True, verbose_name='考生答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='实得分数')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='批改备注')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='批改人')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestion', verbose_name='试卷题目')),
            ],
            options={
                'verbose_name': '作答记录',
                'verbose_name_plural': '作答记录',
                'db_table': 'exam_answers',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='交卷时间')),
                ('status', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已交卷'), (3, '异常交卷')], default=0, verbose_name='考试状态')),
                ('objective_score', models.IntegerField(default=0, verbose_name='客观题总分')),
                ('subjective_score', models.IntegerField(default=0, verbose_name='主观题总分')),
                ('total_score', models.IntegerField(default=0, verbose_name='总成绩')),
                ('is_graded', models.BooleanField(default=False, verbose_name='批改完成标记')),
                ('cheat_flag', models.BooleanField(default=False, verbose_name='防作弊标记')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='考试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='考生')),
            ],
            options={
                'verbose_name': '考生试卷',
                'verbose_name_plural': '考生试卷',
                'db_table': 'exam_papers',
                'unique_together': {('exam', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'user'], name='exam_questi_exam_id_60517f_idx'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['question'], name='exam_answer_questio_db1085_idx'),
        ),
    ]
