# Generated by Django 6.0.4 on 2026-05-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_add_assigned_grader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatlog',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam', verbose_name='考试'),
        ),
        migrations.AlterField(
            model_name='cheatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='考生'),
        ),
        migrations.CreateModel(
            name='GradePublish',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='考试')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='批改员')),
            ],
            options={
                'verbose_name': '批改发布记录',
                'verbose_name_plural': '批改发布记录',
                'db_table': 'grade_publishes',
                'unique_together': {('exam', 'grader')},
            },
        ),
    ]
