# Generated by Django 6.0.4 on 2026-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_gradepublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ai_grade_enabled',
            field=models.BooleanField(default=False, verbose_name='AI 自动批改'),
        ),
    ]
