# Generated by Django 6.0.4 on 2026-05-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeFavorite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='收藏ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student', verbose_name='学生')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.questiontemplate', verbose_name='题目模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='辅导员')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
                'db_table': 'practice_favorites',
                'indexes': [models.Index(fields=['user', 'created_at'], name='practice_fa_user_id_80b3c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PracticeProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='进度ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否已答对')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student', verbose_name='学生')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.questiontemplate', verbose_name='题目模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='辅导员')),
            ],
            options={
                'verbose_name': '练习进度',
                'verbose_name_plural': '练习进度',
                'db_table': 'practice_progresses',
                'unique_together': {('user', 'student', 'template')},
            },
        ),
    ]
