# Generated by Django 6.0.4 on 2026-05-03 14:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practicefavorite',
            unique_together={('user', 'student', 'template')},
        ),
    ]
