# Generated by Django 6.0.4 on 2026-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_practicefavorite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicefavorite',
            name='correct_answer',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='正确答案'),
        ),
        migrations.AddField(
            model_name='practicefavorite',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='practicefavorite',
            name='question_title',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='题目题干'),
        ),
        migrations.AddField(
            model_name='practicefavorite',
            name='question_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='题型'),
        ),
    ]
